### PR TITLE
Added option to install GalliumOS (or Ubuntu) with Steam and/or Minecraft

### PR DESCRIPTION
**Pull request by Firminator**
* added much-needed option to install Steam
* added clarification that GalliumOS is installed

### CODE REVIEW

**Comment by Firminator** [comment]
For -r CHRX lists the following versions:
> -r RELEASE      distribution release number or name [latest]
>                    galliumos: latest, 2.0, xenon, nightly
>                     ubuntu etc: latest, lts, dev, 16.04.1, xenial, etc
>                     fedora: latest, 23, 24, 25

In my mind a major rewrite for adding Fedora is needed for the following part:
```
#select Ubuntu version
useBeta=""
if [ "$ubuntu_package" != "galliumos" ]; then
	validVersions=('<lts>' '<latest>' '<dev>' '<15.10>' '<15.04>' '<14.10>' '<14.04>');
	echo -e "\nEnter the Ubuntu version to install. Valid options are `echo ${validVersions[*]}`. 
If no (valid) version is entered, 'latest' will be used."
	read -p "" ubuntu_version	

	versionValid=$(echo ${validVersions[*]} | grep "<$ubuntu_version>")
	if [[ "$ubuntu_version" = "" || "$versionValid" = "" ]]; then
		ubuntu_version="latest"
	fi
else
    read -p "Do you wish use the latest beta version? [Y/n] "
    [[ "$REPLY" != "n" && "$REPLY" != "N" ]] && useBeta="-r nightly"
fi
```

Maybe Fedora (and Ubuntu) should be separated out (as GalliumOS is the recommended choice anyways) and added as an additional Menu Option, something like this (new/renamed functions):
```
1) clear;
chrx_galliumos;
menu_kodi;
2) clear;
chrx_ubuntu;
menu_kodi;
3) clear;
 chrx_fedora;
menu_kodi;
```
This would help keeping the releases and future changes to it separate, but it would be major code change.

**Comment by MattDevo** [comment]
at this point, why wouldn't someone just use chrx instead of my script? =P

**Comment by Firminator** [comment]
Convenience and E-Zness. Just one script needed instead of two. You guys should unite your efforts :)

**Comment by MattDevo** [comment]
yeah if I can get chrx to add the RW_LEGACY firmware update, then I can drop the dual boot-GaOS/Ubuntu part of things.  It's only there for legacy reasons anyway

**Comment by Firminator** [comment]
Good call. Less code less worries.
On a sidenote I just realized that Steam doesn't even install due to an outdated link in chrx... oh well.

**Pull request closed without merging**
